import sqlite3
conn = sqlite3.connect("/opt/ai-video-platform/backend/data.db")
cur = conn.cursor()
cur.execute("UPDATE voice_profiles SET voice_id='longxiaoxia_v2', provider='dashscope' WHERE voice_id='zh-CN-XiaoxiaoNeural'")
print(f"Updated ÏþÏþ: {cur.rowcount}")
cur.execute("UPDATE voice_profiles SET voice_id='longxiaochun_v2', provider='dashscope' WHERE voice_id='zh-CN-XiaoyiNeural'")
print(f"Updated ÏþÒÁ: {cur.rowcount}")
cur.execute("UPDATE voice_profiles SET voice_id='longxiaobai_v2', provider='dashscope' WHERE voice_id='zh-CN-YunxiNeural'")
print(f"Updated ÔÆÏ£: {cur.rowcount}")
cur.execute("UPDATE voice_profiles SET voice_id='longxiaocheng_v2', provider='dashscope' WHERE voice_id='zh-CN-YunjianNeural'")
print(f"Updated ÔÆ½¡: {cur.rowcount}")
cur.execute("UPDATE voice_profiles SET voice_id='longwan_v2', provider='dashscope' WHERE voice_id='zh-CN-YunyangNeural'")
print(f"Updated ÔÆÑï: {cur.rowcount}")
cur.execute("UPDATE voice_profiles SET voice_id='longanran', provider='dashscope' WHERE voice_id='zh-CN-YunxiaNeural'")
print(f"Updated ÔÆÏÄ: {cur.rowcount}")
cur.execute("UPDATE voice_profiles SET voice_id='sambert-zhimao-v1', provider='dashscope' WHERE voice_id='zh-CN-liaoning-XiaobeiNeural'")
print(f"Updated Ïþ±±: {cur.rowcount}")
cur.execute("UPDATE voice_profiles SET voice_id='sambert-zhichu-v1', provider='dashscope' WHERE voice_id='zh-CN-shaanxi-XiaoniNeural'")
print(f"Updated ÏþÄÝ: {cur.rowcount}")
conn.commit()
conn.close()
print("Done")